# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170920_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='favoriteFood',
            new_name='favoritefood',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='favoriteToy',
            new_name='favoritetoy',
        ),
    ]
